// Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"strings"
)

type Function struct {
	Name   string
	Params []Param
}

type Param struct {
	Name string
	Type string
}

func main() {
	input := flag.String("input", "vendor/github.com/NVIDIA/go-nvml/pkg/nvml/nvml.go", "Input file")
	output := flag.String("output", "pkg/gpu/mocknvml/bridge/bridge_generated.go", "Output file")
	flag.Parse()

	functions, err := parseCWrappers(*input)
	if err != nil {
		log.Fatalf("Failed to parse: %v", err)
	}

	log.Printf("Found %d C wrapper functions", len(functions))

	code := generateCompleteBridge(functions)

	formatted, err := format.Source([]byte(code))
	if err != nil {
		log.Printf("Warning: formatting failed: %v", err)
		formatted = []byte(code)
	}

	if err := os.WriteFile(*output, formatted, 0644); err != nil {
		log.Fatalf("Failed to write: %v", err)
	}

	log.Printf("Successfully generated %s", *output)
}

func parseCWrappers(filename string) ([]Function, error) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, filename, nil, 0)
	if err != nil {
		return nil, err
	}

	var functions []Function

	ast.Inspect(node, func(n ast.Node) bool {
		funcDecl, ok := n.(*ast.FuncDecl)
		if !ok || !strings.HasPrefix(funcDecl.Name.Name, "nvml") {
			return true
		}

		f := Function{Name: funcDecl.Name.Name}

		if funcDecl.Type.Params != nil {
			for _, field := range funcDecl.Type.Params.List {
				paramType := exprToString(field.Type)
				if len(field.Names) > 0 {
					for _, name := range field.Names {
						f.Params = append(f.Params, Param{
							Name: strings.ToLower(name.Name[:1]) + name.Name[1:],
							Type: paramType,
						})
					}
				}
			}
		}

		functions = append(functions, f)
		return true
	})

	return functions, nil
}

func exprToString(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return e.Name
	case *ast.SelectorExpr:
		return exprToString(e.X) + "." + e.Sel.Name
	case *ast.ArrayType:
		return "[]" + exprToString(e.Elt)
	case *ast.StarExpr:
		return "*" + exprToString(e.X)
	default:
		return "interface{}"
	}
}

func generateCompleteBridge(functions []Function) string {
	var buf bytes.Buffer

	// Write complete header with main() and helpers
	buf.WriteString(`// Code generated by cmd/generate-bridge. DO NOT EDIT.
// Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.

package main

/*
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <stdint.h>

typedef int nvmlReturn_t;
typedef void* nvmlDevice_t;

typedef struct nvmlPciInfo_st {
    char busIdLegacy[16];
    unsigned int domain;
    unsigned int bus;
    unsigned int device;
    unsigned int pciDeviceId;
    unsigned int pciSubSystemId;
    char busId[32];
} nvmlPciInfo_t;

typedef struct nvmlMemory_st {
    unsigned long long total;
    unsigned long long free;
    unsigned long long used;
} nvmlMemory_t;

typedef struct nvmlProcessInfo_st {
    unsigned int pid;
    unsigned long long usedGpuMemory;
} nvmlProcessInfo_t;

#define NVML_SUCCESS                    0
#define NVML_ERROR_UNINITIALIZED        1
#define NVML_ERROR_INVALID_ARGUMENT     2
#define NVML_ERROR_NOT_SUPPORTED        3
#define NVML_ERROR_INSUFFICIENT_SIZE    7
#define NVML_ERROR_TIMEOUT              14
#define NVML_ERROR_UNKNOWN              999

// Forward declaration of our device handle getter
extern nvmlReturn_t nvmlDeviceGetHandleByIndex_v2(unsigned int index, void* device);

// Debug mode - check MOCK_NVML_DEBUG env var once at startup
static int debugChecked = 0;
static int debugEnabled = 0;

static int isDebugEnabled() {
    if (!debugChecked) {
        debugChecked = 1;
        debugEnabled = (getenv("MOCK_NVML_DEBUG") != NULL);
    }
    return debugEnabled;
}

// C stub function for internal export table
// This gets called by nvidia-smi via the export table function pointers
// Pattern observed: arg0=device_index (0-7), arg1=output_ptr, arg2=0x22 (flags), arg3=our_stub_ptr
static nvmlReturn_t internalStubFunction(void* arg0, void* arg1, void* arg2, void* arg3) {
    // Interpret as device index lookup
    uintptr_t rawArg0 = (uintptr_t)arg0;
    uintptr_t rawArg2 = (uintptr_t)arg2;

    // Device index lookup: small index, valid stack pointer, flags 0x22
    if (rawArg0 < 32 && rawArg2 == 0x22) {
        void** outputPtr = (void**)arg1;
        if (outputPtr != NULL) {
            nvmlReturn_t ret = nvmlDeviceGetHandleByIndex_v2((unsigned int)rawArg0, outputPtr);
            if (isDebugEnabled()) {
                fprintf(stderr, "[C-STUB] DeviceGetHandle(%u) -> ret=%d, handle=%p\n",
                        (unsigned int)rawArg0, ret, *outputPtr);
            }
            return ret;
        }
    }

    // Non-device call - return SUCCESS to acknowledge
    return NVML_SUCCESS;
}

// Get address of stub function
static void* getInternalStubAddress() {
    return (void*)internalStubFunction;
}
*/
import "C"
import (
	"fmt"
	"os"
	"sync"
	"unsafe"

	"github.com/NVIDIA/go-nvml/pkg/nvml"
	"github.com/NVIDIA/k8s-test-infra/pkg/gpu/mocknvml/engine"
)

// errorStringCache caches C strings for nvmlErrorString to avoid memory leaks.
// Real NVML returns static strings, so caching matches expected behavior.
var (
	errorStringCache   = make(map[nvml.Return]*C.char)
	errorStringCacheMu sync.Mutex
)

// debugEnabled controls whether debug messages are printed
var debugEnabled = os.Getenv("MOCK_NVML_DEBUG") != ""

// debugLog prints to stderr only if MOCK_NVML_DEBUG is set
func debugLog(format string, args ...any) {
	if debugEnabled {
		fmt.Fprintf(os.Stderr, format, args...)
	}
}

func main() {
	// Required for buildmode=c-shared
}

func toReturn(ret nvml.Return) C.nvmlReturn_t {
	return C.nvmlReturn_t(ret)
}

func goStringToC(s string, buf *C.char, length C.uint) C.nvmlReturn_t {
	if buf == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	if len(s)+1 > int(length) {
		return C.NVML_ERROR_INSUFFICIENT_SIZE
	}
	cStr := C.CString(s)
	defer C.free(unsafe.Pointer(cStr))
	C.strcpy(buf, cStr)
	return C.NVML_SUCCESS
}

`)

	// Generate all functions
	for _, f := range functions {
		buf.WriteString(generateFunction(f))
		buf.WriteString("\n")
	}

	// Add non-versioned symbol aliases that nvidia-smi expects
	buf.WriteString(`
// Non-versioned symbol aliases for nvidia-smi compatibility
// These symbols are required because nvidia-smi looks for unversioned symbols

//export nvmlInit
func nvmlInit() C.nvmlReturn_t {
	return nvmlInit_v2()
}

//export nvmlDeviceGetCount
func nvmlDeviceGetCount(deviceCount unsafe.Pointer) C.nvmlReturn_t {
	return nvmlDeviceGetCount_v2(deviceCount)
}

//export nvmlDeviceGetHandleByIndex
func nvmlDeviceGetHandleByIndex(index C.uint, nvmlDevice unsafe.Pointer) C.nvmlReturn_t {
	return nvmlDeviceGetHandleByIndex_v2(index, nvmlDevice)
}

//export nvmlDeviceGetPciInfo
func nvmlDeviceGetPciInfo(nvmlDevice unsafe.Pointer, pci unsafe.Pointer) C.nvmlReturn_t {
	return nvmlDeviceGetPciInfo_v3(nvmlDevice, pci)
}

//export nvmlDeviceGetComputeRunningProcesses
func nvmlDeviceGetComputeRunningProcesses(nvmlDevice unsafe.Pointer, infoCount unsafe.Pointer, infos unsafe.Pointer) C.nvmlReturn_t {
	return nvmlDeviceGetComputeRunningProcesses_v3(nvmlDevice, infoCount, infos)
}

//export nvmlDeviceGetGraphicsRunningProcesses
func nvmlDeviceGetGraphicsRunningProcesses(nvmlDevice unsafe.Pointer, infoCount unsafe.Pointer, infos unsafe.Pointer) C.nvmlReturn_t {
	return nvmlDeviceGetGraphicsRunningProcesses_v3(nvmlDevice, infoCount, infos)
}

//export nvmlDeviceGetMPSComputeRunningProcesses
func nvmlDeviceGetMPSComputeRunningProcesses(nvmlDevice unsafe.Pointer, infoCount unsafe.Pointer, infos unsafe.Pointer) C.nvmlReturn_t {
	return nvmlDeviceGetMPSComputeRunningProcesses_v3(nvmlDevice, infoCount, infos)
}

//export nvmlDeviceGetHandleByPciBusId
func nvmlDeviceGetHandleByPciBusId(pciBusId *C.char, nvmlDevice unsafe.Pointer) C.nvmlReturn_t {
	return nvmlDeviceGetHandleByPciBusId_v2(pciBusId, nvmlDevice)
}

//export nvmlComputeInstanceGetInfo
func nvmlComputeInstanceGetInfo(computeInstance unsafe.Pointer, info unsafe.Pointer) C.nvmlReturn_t {
	return nvmlComputeInstanceGetInfo_v2(computeInstance, info)
}

//export nvmlDeviceGetAttributes
func nvmlDeviceGetAttributes(nvmlDevice unsafe.Pointer, attributes unsafe.Pointer) C.nvmlReturn_t {
	return nvmlDeviceGetAttributes_v2(nvmlDevice, attributes)
}

//export nvmlDeviceGetDriverModel
func nvmlDeviceGetDriverModel(nvmlDevice unsafe.Pointer, current unsafe.Pointer, pending unsafe.Pointer) C.nvmlReturn_t {
	return C.NVML_ERROR_NOT_SUPPORTED
}

//export nvmlDeviceGetGpuInstancePossiblePlacements
func nvmlDeviceGetGpuInstancePossiblePlacements(nvmlDevice unsafe.Pointer, profileId C.uint, placements unsafe.Pointer, count unsafe.Pointer) C.nvmlReturn_t {
	return nvmlDeviceGetGpuInstancePossiblePlacements_v2(nvmlDevice, profileId, placements, count)
}

//export nvmlDeviceGetGridLicensableFeatures
func nvmlDeviceGetGridLicensableFeatures(nvmlDevice unsafe.Pointer, features unsafe.Pointer) C.nvmlReturn_t {
	return nvmlDeviceGetGridLicensableFeatures_v4(nvmlDevice, features)
}

//export nvmlDeviceGetNvLinkRemotePciInfo
func nvmlDeviceGetNvLinkRemotePciInfo(nvmlDevice unsafe.Pointer, link C.uint, pci unsafe.Pointer) C.nvmlReturn_t {
	return nvmlDeviceGetNvLinkRemotePciInfo_v2(nvmlDevice, link, pci)
}

//export nvmlDeviceRemoveGpu
func nvmlDeviceRemoveGpu(pciInfo unsafe.Pointer, gpuState unsafe.Pointer, linkState unsafe.Pointer) C.nvmlReturn_t {
	return nvmlDeviceRemoveGpu_v2(pciInfo, gpuState, linkState)
}

//export nvmlEventSetWait
func nvmlEventSetWait(set unsafe.Pointer, data unsafe.Pointer, timeoutms C.uint) C.nvmlReturn_t {
	return nvmlEventSetWait_v2(set, data, timeoutms)
}

//export nvmlVgpuInstanceGetLicenseInfo
func nvmlVgpuInstanceGetLicenseInfo(vgpuInstance unsafe.Pointer, info unsafe.Pointer) C.nvmlReturn_t {
	return nvmlVgpuInstanceGetLicenseInfo_v2(vgpuInstance, info)
}

// Internal export table for nvidia-smi compatibility
// Based on reverse engineering: table[0] = size (must be > 648), table[648/8] = function pointer
// Table needs to be large enough for all offsets nvidia-smi might access
var internalExportTable [256]uintptr
var exportTableInitialized = false

func initExportTable() {
	if exportTableInitialized {
		return
	}
	// Set up the export table
	// Offset 0: size field (must be > 648 = 0x288)
	internalExportTable[0] = 0x1000

	// Get function pointer for our C stub
	stubPtr := uintptr(C.getInternalStubAddress())
	debugLog("[MOCK-NVML] C stub function address: %p\n", C.getInternalStubAddress())

	// Fill all potential function pointer slots with the stub
	for i := 1; i < 256; i++ {
		internalExportTable[i] = stubPtr
	}

	exportTableInitialized = true
	debugLog("[MOCK-NVML] Export table initialized with stub at %p\n", unsafe.Pointer(stubPtr))
}

// Internal function used by nvidia-smi for version verification
// This is a proprietary NVIDIA internal API that nvidia-smi calls to verify
// compatibility between nvidia-smi and the NVML library.
//export nvmlInternalGetExportTable
func nvmlInternalGetExportTable(ppExportTable unsafe.Pointer, guid unsafe.Pointer) C.nvmlReturn_t {
	// Initialize export table on first call
	initExportTable()

	// Debug: print the GUID being requested
	var guidStr string
	if guid != nil {
		guidBytes := (*[16]byte)(guid)
		guidStr = fmt.Sprintf("%02x%02x%02x%02x-%02x%02x-%02x%02x-%02x%02x-%02x%02x%02x%02x%02x%02x",
			guidBytes[3], guidBytes[2], guidBytes[1], guidBytes[0],
			guidBytes[5], guidBytes[4],
			guidBytes[7], guidBytes[6],
			guidBytes[8], guidBytes[9],
			guidBytes[10], guidBytes[11], guidBytes[12], guidBytes[13], guidBytes[14], guidBytes[15])
		debugLog("[MOCK-NVML] nvmlInternalGetExportTable called with GUID: %s\n", guidStr)
	}

	// Only handle the known GUID for device enumeration
	knownGUID := "6c3efec4-8fc9-4e6c-a327-ee696e12f7c4"
	if guidStr != knownGUID {
		debugLog("[MOCK-NVML] Unknown GUID %s - returning NOT_SUPPORTED\n", guidStr)
		return C.NVML_ERROR_NOT_SUPPORTED
	}

	// Return the internal export table
	if ppExportTable != nil {
		*(*unsafe.Pointer)(ppExportTable) = unsafe.Pointer(&internalExportTable[0])
	}
	debugLog("[MOCK-NVML] nvmlInternalGetExportTable returning SUCCESS with table at %p\n", &internalExportTable[0])
	return C.NVML_SUCCESS
}
`)

	return buf.String()
}

func generateFunction(f Function) string {
	var buf bytes.Buffer

	// Special case for nvmlErrorString which returns const char*
	if f.Name == "nvmlErrorString" {
		return generateErrorStringFunction()
	}

	fmt.Fprintf(&buf, "//export %s\n", f.Name)
	fmt.Fprintf(&buf, "func %s(", f.Name)
	for i, p := range f.Params {
		if i > 0 {
			buf.WriteString(", ")
		}
		// Special handling for string input parameters - they should be *C.char
		paramType := getCType(p.Type)
		if paramType == "string" && needsCCharParam(f.Name, p.Name) {
			paramType = "*C.char"
		}
		fmt.Fprintf(&buf, "%s %s", p.Name, paramType)
	}
	buf.WriteString(") C.nvmlReturn_t {\n")

	// Check for custom implementations
	if impl := getImplementation(f.Name); impl != "" {
		buf.WriteString(impl)
		buf.WriteString("\n")
	} else {
		// Log unimplemented functions to help debug
		fmt.Fprintf(&buf, "\tdebugLog(\"[NVML-STUB] %s called (NOT IMPLEMENTED)\\n\")\n", f.Name)
		buf.WriteString("\treturn C.NVML_ERROR_NOT_SUPPORTED\n")
	}

	buf.WriteString("}\n")
	return buf.String()
}

func generateErrorStringFunction() string {
	return `//export nvmlErrorString
func nvmlErrorString(result C.nvmlReturn_t) *C.char {
	ret := nvml.Return(result)

	errorStringCacheMu.Lock()
	defer errorStringCacheMu.Unlock()

	if cached, ok := errorStringCache[ret]; ok {
		return cached
	}

	str := nvml.ErrorString(ret)
	cStr := C.CString(str)
	errorStringCache[ret] = cStr
	return cStr
}
`
}

// needsCCharParam returns true if the parameter should be *C.char instead of string
func needsCCharParam(funcName, paramName string) bool {
	// Functions that take string inputs from C should use *C.char
	stringInputFuncs := map[string][]string{
		"nvmlDeviceGetHandleByUUID":        {"uuid"},
		"nvmlDeviceGetHandleByPciBusId_v1": {"pciBusId"},
		"nvmlDeviceGetHandleByPciBusId_v2": {"pciBusId"},
		"nvmlDeviceGetHandleBySerial":      {"serial"},
	}

	if params, ok := stringInputFuncs[funcName]; ok {
		for _, p := range params {
			if p == paramName {
				return true
			}
		}
	}
	return false
}

func getImplementation(funcName string) string {
	switch funcName {
	case "nvmlInit", "nvmlInit_v2":
		return `	ret := engine.GetEngine().Init()
	return toReturn(ret)`
	case "nvmlInitWithFlags":
		return `	ret := engine.GetEngine().Init()
	return toReturn(ret)`
	case "nvmlShutdown":
		return `	ret := engine.GetEngine().Shutdown()
	return toReturn(ret)`
	case "nvmlDeviceGetCount", "nvmlDeviceGetCount_v2":
		return `	if deviceCount == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	count, ret := engine.GetEngine().DeviceGetCount()
	if ret == nvml.SUCCESS {
		*(*C.uint)(deviceCount) = C.uint(count)
	}
	return toReturn(ret)`
	case "nvmlDeviceGetHandleByIndex", "nvmlDeviceGetHandleByIndex_v2":
		return `	if nvmlDevice == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	debugLog("[NVML] nvmlDeviceGetHandleByIndex(%d)\n", index)
	handle, ret := engine.GetEngine().DeviceGetHandleByIndex(int(index))
	if ret == nvml.SUCCESS {
		*(*C.nvmlDevice_t)(nvmlDevice) = *(*C.nvmlDevice_t)(unsafe.Pointer(&handle))
		debugLog("[NVML]   -> handle=%p ret=%d\n", unsafe.Pointer(handle), ret)
	}
	return toReturn(ret)`
	case "nvmlDeviceGetHandleByUUID":
		return `	if nvmlDevice == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	goUUID := C.GoString(uuid)
	handle, ret := engine.GetEngine().DeviceGetHandleByUUID(goUUID)
	if ret == nvml.SUCCESS {
		*(*C.nvmlDevice_t)(nvmlDevice) = *(*C.nvmlDevice_t)(unsafe.Pointer(&handle))
	}
	return toReturn(ret)`
	case "nvmlDeviceGetHandleByPciBusId_v2", "nvmlDeviceGetHandleByPciBusId_v1":
		return `	if nvmlDevice == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	goPciBusId := C.GoString(pciBusId)
	handle, ret := engine.GetEngine().DeviceGetHandleByPciBusId(goPciBusId)
	if ret == nvml.SUCCESS {
		*(*C.nvmlDevice_t)(nvmlDevice) = *(*C.nvmlDevice_t)(unsafe.Pointer(&handle))
	}
	return toReturn(ret)`
	case "nvmlDeviceGetName":
		return `	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	devName, ret := dev.GetName()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	return goStringToC(devName, (*C.char)(name), length)`
	case "nvmlDeviceGetUUID":
		return `	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	devUUID, ret := dev.GetUUID()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	return goStringToC(devUUID, (*C.char)(uuid), length)`
	case "nvmlDeviceGetPciInfo_v3":
		return `	if pci == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	info, ret := dev.GetPciInfo()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	// Copy busId bytes directly
	cPci := (*C.nvmlPciInfo_t)(pci)
	for i := 0; i < 32 && i < len(info.BusId); i++ {
		cPci.busId[i] = C.char(info.BusId[i])
	}
	cPci.domain = C.uint(info.Domain)
	cPci.bus = C.uint(info.Bus)
	cPci.device = C.uint(info.Device)
	cPci.pciDeviceId = C.uint(info.PciDeviceId)
	cPci.pciSubSystemId = C.uint(info.PciSubSystemId)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetMemoryInfo":
		return `	if memory == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	info, ret := dev.GetMemoryInfo()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	cMemory := (*C.nvmlMemory_t)(memory)
	cMemory.total = C.ulonglong(info.Total)
	cMemory.free = C.ulonglong(info.Free)
	cMemory.used = C.ulonglong(info.Used)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetComputeRunningProcesses_v3":
		return `	if infoCount == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	processes, ret := dev.GetComputeRunningProcesses()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*uint32)(infoCount) = uint32(len(processes))
	return toReturn(nvml.SUCCESS)`
	case "nvmlDeviceGetGraphicsRunningProcesses_v3":
		return `	if infoCount == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	processes, ret := dev.GetGraphicsRunningProcesses()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*uint32)(infoCount) = uint32(len(processes))
	return toReturn(nvml.SUCCESS)`
	case "nvmlSystemGetDriverVersion":
		return `	if version == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	driverVersion, ret := engine.GetEngine().SystemGetDriverVersion()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	return goStringToC(driverVersion, (*C.char)(version), length)`
	case "nvmlSystemGetNVMLVersion":
		return `	if version == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	nvmlVersion, ret := engine.GetEngine().SystemGetNVMLVersion()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	return goStringToC(nvmlVersion, (*C.char)(version), length)`
	case "nvmlSystemGetCudaDriverVersion", "nvmlSystemGetCudaDriverVersion_v2":
		return `	if cudaDriverVersion == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	ver, ret := engine.GetEngine().SystemGetCudaDriverVersion()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.int)(cudaDriverVersion) = C.int(ver)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetSerial":
		return `	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	devSerial, ret := dev.GetSerial()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	return goStringToC(devSerial, (*C.char)(serial), length)`
	case "nvmlDeviceGetVbiosVersion":
		return `	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	vbios, ret := dev.GetVbiosVersion()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	return goStringToC(vbios, (*C.char)(version), length)`
	case "nvmlDeviceGetBoardPartNumber":
		return `	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	pn, ret := dev.GetBoardPartNumber()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	return goStringToC(pn, (*C.char)(partNumber), length)`
	case "nvmlDeviceGetBrand":
		return `	if _type == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	brand, ret := dev.GetBrand()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(_type) = C.uint(brand)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetIndex":
		return `	if index == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	idx, ret := dev.GetIndex()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(index) = C.uint(idx)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetMinorNumber":
		return `	if minorNumber == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	minor, ret := dev.GetMinorNumber()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(minorNumber) = C.uint(minor)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetInforomVersion":
		return `	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	// object is passed by value as an enum
	ver, ret := dev.GetInforomVersion(nvml.InforomObject(uintptr(object)))
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	return goStringToC(ver, (*C.char)(version), length)`
	case "nvmlDeviceGetInforomImageVersion":
		return `	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	ver, ret := dev.GetInforomImageVersion()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	return goStringToC(ver, (*C.char)(version), length)`
	case "nvmlDeviceGetTemperature":
		return `	if temp == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	// sensorType is passed by value as an enum, cast from unsafe.Pointer
	sensor := nvml.TemperatureSensors(uintptr(sensorType))
	temperature, ret := dev.GetTemperature(sensor)
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(temp) = C.uint(temperature)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetTemperatureThreshold":
		return `	if temp == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	// thresholdType is passed by value as an enum
	threshold := nvml.TemperatureThresholds(uintptr(thresholdType))
	temperature, ret := dev.GetTemperatureThreshold(threshold)
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(temp) = C.uint(temperature)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetPowerUsage":
		return `	if power == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	powerUsage, ret := dev.GetPowerUsage()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(power) = C.uint(powerUsage)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetPowerManagementLimit":
		return `	if limit == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	powerLimit, ret := dev.GetPowerManagementLimit()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(limit) = C.uint(powerLimit)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetPowerManagementDefaultLimit":
		return `	if defaultLimit == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	limit, ret := dev.GetPowerManagementDefaultLimit()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(defaultLimit) = C.uint(limit)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetPowerManagementLimitConstraints":
		return `	if minLimit == nil || maxLimit == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	minVal, maxVal, ret := dev.GetPowerManagementLimitConstraints()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(minLimit) = C.uint(minVal)
	*(*C.uint)(maxLimit) = C.uint(maxVal)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetEnforcedPowerLimit":
		return `	if limit == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	enforcedLimit, ret := dev.GetEnforcedPowerLimit()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(limit) = C.uint(enforcedLimit)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetClockInfo":
		return `	if clock == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	// _type is passed by value as an enum
	clockType := nvml.ClockType(uintptr(_type))
	clockVal, ret := dev.GetClockInfo(clockType)
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(clock) = C.uint(clockVal)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetMaxClockInfo":
		return `	if clock == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	// _type is passed by value as an enum
	clockType := nvml.ClockType(uintptr(_type))
	maxClock, ret := dev.GetMaxClockInfo(clockType)
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(clock) = C.uint(maxClock)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetApplicationsClock":
		return `	if clockMHz == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	// clockType is passed by value as an enum
	clock, ret := dev.GetApplicationsClock(nvml.ClockType(uintptr(clockType)))
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(clockMHz) = C.uint(clock)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetDefaultApplicationsClock":
		return `	if clockMHz == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	// clockType is passed by value as an enum
	clock, ret := dev.GetDefaultApplicationsClock(nvml.ClockType(uintptr(clockType)))
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(clockMHz) = C.uint(clock)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetUtilizationRates":
		return `	if utilization == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	util, ret := dev.GetUtilizationRates()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	// nvmlUtilization_t has two fields: gpu and memory (both uint)
	type nvmlUtilization struct {
		gpu    C.uint
		memory C.uint
	}
	cUtil := (*nvmlUtilization)(utilization)
	cUtil.gpu = C.uint(util.Gpu)
	cUtil.memory = C.uint(util.Memory)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetPerformanceState":
		return `	if pState == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	state, ret := dev.GetPerformanceState()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(pState) = C.uint(state)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetPersistenceMode":
		return `	if mode == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	persistMode, ret := dev.GetPersistenceMode()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(mode) = C.uint(persistMode)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetComputeMode":
		return `	if mode == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	computeMode, ret := dev.GetComputeMode()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(mode) = C.uint(computeMode)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetEccMode":
		return `	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	curMode, pendMode, ret := dev.GetEccMode()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	if current != nil {
		*(*C.uint)(current) = C.uint(curMode)
	}
	if pending != nil {
		*(*C.uint)(pending) = C.uint(pendMode)
	}
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetFanSpeed":
		return `	if speed == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	fanSpeed, ret := dev.GetFanSpeed()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(speed) = C.uint(fanSpeed)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetFanSpeed_v2":
		return `	if speed == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	// fan is passed by value
	fanIndex := int(uintptr(fan))
	fanSpeed, ret := dev.GetFanSpeed_v2(fanIndex)
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(speed) = C.uint(fanSpeed)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetNumFans":
		return `	if numFans == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	count, ret := dev.GetNumFans()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(numFans) = C.uint(count)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetCurrPcieLinkGeneration":
		return `	if currLinkGen == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	gen, ret := dev.GetCurrPcieLinkGeneration()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(currLinkGen) = C.uint(gen)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetMaxPcieLinkGeneration":
		return `	if maxLinkGen == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	gen, ret := dev.GetMaxPcieLinkGeneration()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(maxLinkGen) = C.uint(gen)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetCurrPcieLinkWidth":
		return `	if currLinkWidth == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	width, ret := dev.GetCurrPcieLinkWidth()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(currLinkWidth) = C.uint(width)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetMaxPcieLinkWidth":
		return `	if maxLinkWidth == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	width, ret := dev.GetMaxPcieLinkWidth()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(maxLinkWidth) = C.uint(width)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetBAR1MemoryInfo":
		return `	if bar1Memory == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	info, ret := dev.GetBAR1MemoryInfo()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	// nvmlBAR1Memory_t has: bar1Total, bar1Free, bar1Used (ulonglong)
	type nvmlBAR1Memory struct {
		bar1Total C.ulonglong
		bar1Free  C.ulonglong
		bar1Used  C.ulonglong
	}
	cBar1 := (*nvmlBAR1Memory)(bar1Memory)
	cBar1.bar1Total = C.ulonglong(info.Bar1Total)
	cBar1.bar1Free = C.ulonglong(info.Bar1Free)
	cBar1.bar1Used = C.ulonglong(info.Bar1Used)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetCurrentClocksThrottleReasons":
		return `	if clocksThrottleReasons == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	reasons, ret := dev.GetCurrentClocksThrottleReasons()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.ulonglong)(clocksThrottleReasons) = C.ulonglong(reasons)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetTotalEccErrors":
		return `	if eccCounts == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	// errorType and counterType are passed by value as enums
	count, ret := dev.GetTotalEccErrors(nvml.MemoryErrorType(uintptr(errorType)), nvml.EccCounterType(uintptr(counterType)))
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.ulonglong)(eccCounts) = C.ulonglong(count)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetMemoryErrorCounter":
		return `	if count == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	// errorType, counterType, locationType are passed by value as enums
	errCount, ret := dev.GetMemoryErrorCounter(nvml.MemoryErrorType(uintptr(errorType)), nvml.EccCounterType(uintptr(counterType)), nvml.MemoryLocation(uintptr(locationType)))
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.ulonglong)(count) = C.ulonglong(errCount)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetRetiredPages":
		return `	if pageCount == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	// cause is passed by value as an enum
	_, ret := dev.GetRetiredPages(nvml.PageRetirementCause(uintptr(cause)))
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(pageCount) = 0
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetRetiredPages_v2":
		return `	if pageCount == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	// cause is passed by value as an enum
	_, _, ret := dev.GetRetiredPages_v2(nvml.PageRetirementCause(uintptr(cause)))
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(pageCount) = 0
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetRetiredPagesPendingStatus":
		return `	if isPending == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	pending, ret := dev.GetRetiredPagesPendingStatus()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(isPending) = C.uint(pending)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetRemappedRows":
		return `	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	correctable, uncorrectable, pendingVal, failureVal, ret := dev.GetRemappedRows()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	if corrRows != nil {
		*(*C.uint)(corrRows) = C.uint(correctable)
	}
	if uncRows != nil {
		*(*C.uint)(uncRows) = C.uint(uncorrectable)
	}
	if isPending != nil {
		if pendingVal {
			*(*C.uint)(isPending) = 1
		} else {
			*(*C.uint)(isPending) = 0
		}
	}
	if failureOccurred != nil {
		if failureVal {
			*(*C.uint)(failureOccurred) = 1
		} else {
			*(*C.uint)(failureOccurred) = 0
		}
	}
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetEncoderUtilization":
		return `	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	util, samplingPeriod, ret := dev.GetEncoderUtilization()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	if utilization != nil {
		*(*C.uint)(utilization) = C.uint(util)
	}
	if samplingPeriodUs != nil {
		*(*C.uint)(samplingPeriodUs) = C.uint(samplingPeriod)
	}
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetDecoderUtilization":
		return `	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	util, samplingPeriod, ret := dev.GetDecoderUtilization()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	if utilization != nil {
		*(*C.uint)(utilization) = C.uint(util)
	}
	if samplingPeriodUs != nil {
		*(*C.uint)(samplingPeriodUs) = C.uint(samplingPeriod)
	}
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetAccountingMode":
		return `	if mode == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	accountingMode, ret := dev.GetAccountingMode()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(mode) = C.uint(accountingMode)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetAccountingBufferSize":
		return `	if bufferSize == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	size, ret := dev.GetAccountingBufferSize()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(bufferSize) = C.uint(size)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetDisplayActive":
		return `	if isActive == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	active, ret := dev.GetDisplayActive()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(isActive) = C.uint(active)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetDisplayMode":
		return `	if display == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	mode, ret := dev.GetDisplayMode()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(display) = C.uint(mode)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetPcieThroughput":
		return `	if value == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	// counter is passed by value as an enum
	throughput, ret := dev.GetPcieThroughput(nvml.PcieUtilCounter(uintptr(counter)))
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(value) = C.uint(throughput)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetPcieReplayCounter":
		return `	if value == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	counter, ret := dev.GetPcieReplayCounter()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(value) = C.uint(counter)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetArchitecture":
		return `	if arch == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	architecture, ret := dev.GetArchitecture()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(arch) = C.uint(architecture)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetCudaComputeCapability":
		return `	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	majorVal, minorVal, ret := dev.GetCudaComputeCapability()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	if major != nil {
		*(*C.int)(major) = C.int(majorVal)
	}
	if minor != nil {
		*(*C.int)(minor) = C.int(minorVal)
	}
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetPowerState":
		return `	if pState == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	state, ret := dev.GetPowerState()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(pState) = C.uint(state)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetMigMode":
		return `	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	curMode, pendMode, ret := dev.GetMigMode()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	if currentMode != nil {
		*(*C.uint)(currentMode) = C.uint(curMode)
	}
	if pendingMode != nil {
		*(*C.uint)(pendingMode) = C.uint(pendMode)
	}
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetMultiGpuBoard":
		return `	if multiGpuBool == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	isMulti, ret := dev.GetMultiGpuBoard()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(multiGpuBool) = C.uint(isMulti)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetBoardId":
		return `	if boardId == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	id, ret := dev.GetBoardId()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(boardId) = C.uint(id)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetEncoderCapacity":
		return `	if encoderCapacity == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	// encoderQueryType is passed by value as an enum
	capacity, ret := dev.GetEncoderCapacity(nvml.EncoderType(uintptr(encoderQueryType)))
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(encoderCapacity) = C.uint(capacity)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetEncoderSessions":
		return `	if sessionCount == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	_, ret := dev.GetEncoderSessions()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(sessionCount) = 0
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetFBCSessions":
		return `	if sessionCount == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	_, ret := dev.GetFBCSessions()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(sessionCount) = 0
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetGpuOperationMode":
		return `	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	curMode, pendMode, ret := dev.GetGpuOperationMode()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	if current != nil {
		*(*C.uint)(current) = C.uint(curMode)
	}
	if pending != nil {
		*(*C.uint)(pending) = C.uint(pendMode)
	}
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetNvLinkState":
		return `	if isActive == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	// link is passed by value
	linkNum := int(uintptr(link))
	state, ret := dev.GetNvLinkState(linkNum)
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(isActive) = C.uint(state)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetNvLinkVersion":
		return `	if version == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	// link is passed by value
	linkNum := int(uintptr(link))
	ver, ret := dev.GetNvLinkVersion(linkNum)
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(version) = C.uint(ver)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetNvLinkCapability":
		return `	if capResult == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	// link and capability are passed by value
	linkNum := int(uintptr(link))
	cap, ret := dev.GetNvLinkCapability(linkNum, nvml.NvLinkCapability(uintptr(capability)))
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	*(*C.uint)(capResult) = C.uint(cap)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetMemoryInfo_v2":
		return `	if memory == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	dev := engine.GetEngine().LookupDevice(uintptr(nvmlDevice))
	if dev == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	info, ret := dev.GetMemoryInfo_v2()
	if ret != nvml.SUCCESS {
		return toReturn(ret)
	}
	// nvmlMemory_v2_t has version, total, reserved, free, used
	type nvmlMemoryV2 struct {
		version  C.uint
		total    C.ulonglong
		reserved C.ulonglong
		free     C.ulonglong
		used     C.ulonglong
	}
	cMemory := (*nvmlMemoryV2)(memory)
	cMemory.version = C.uint(info.Version)
	cMemory.total = C.ulonglong(info.Total)
	cMemory.reserved = C.ulonglong(info.Reserved)
	cMemory.free = C.ulonglong(info.Free)
	cMemory.used = C.ulonglong(info.Used)
	return C.NVML_SUCCESS`
	case "nvmlEventSetCreate":
		return `	if set == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	// Create a fake event set handle (non-null pointer)
	fakeHandle := uintptr(0xEE5E7001)
	*(*uintptr)(set) = fakeHandle
	debugLog("[NVML] nvmlEventSetCreate -> handle=%p\n", unsafe.Pointer(fakeHandle))
	return C.NVML_SUCCESS`
	case "nvmlEventSetFree":
		return `	debugLog("[NVML] nvmlEventSetFree called\n")
	return C.NVML_SUCCESS`
	case "nvmlEventSetWait_v2":
		return `	debugLog("[NVML] nvmlEventSetWait_v2 called (timeout=%d)\n", timeoutms)
	// Return timeout (no events available in mock)
	return C.NVML_ERROR_TIMEOUT`
	case "nvmlDeviceRegisterEvents":
		return `	debugLog("[NVML] nvmlDeviceRegisterEvents called (eventTypes=%d)\n", eventTypes)
	return C.NVML_SUCCESS`
	case "nvmlDeviceGetSupportedEventTypes":
		return `	if eventTypes == nil {
		return C.NVML_ERROR_INVALID_ARGUMENT
	}
	// Return that we support no event types (0)
	*(*C.ulonglong)(eventTypes) = 0
	debugLog("[NVML] nvmlDeviceGetSupportedEventTypes -> 0\n")
	return C.NVML_SUCCESS`
	default:
		return ""
	}
}

func getCType(goType string) string {
	switch {
	case goType == "*byte":
		return "unsafe.Pointer"
	case goType == "string":
		return "string"
	case goType == "uint32":
		return "C.uint"
	case goType == "*uint32":
		return "unsafe.Pointer"
	case goType == "int32":
		return "C.int"
	case goType == "*int32":
		return "unsafe.Pointer"
	case goType == "uint64":
		return "C.ulonglong"
	case goType == "*uint64":
		return "unsafe.Pointer"
	case strings.Contains(goType, "Device") || strings.Contains(goType, "device"):
		return "unsafe.Pointer"
	default:
		return "unsafe.Pointer"
	}
}
